#!/bin/bash

# based on: https://www.a1k.org/forum/index.php?threads/87146/

sudo sh -c 'apt-get update && apt-get -y upgrade; 
apt-get install mc mpg123;
apt install python3-dev python3-distutils python3-pip python3-pyudev python3-websockets build-essential git iptables libraspberrypi-dev;
'
git clone https://github.com/niklasekstrom/a314.git

cd a314/Software && sudo sh -c './install-pi.sh ; sed -i '/net.ipv4.ip_forward=1/s/^#*\s*//g' /etc/sysctl.conf;
sed -i '/exit 0/i \
iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE\
iptables -A FORWARD -i wlan0 -o tap0 -m state --state RELATED,ESTABLISHED -j ACCEPT\
iptables -A FORWARD -i tap0 -o wlan0 -j ACCEPT\
' /etc/rc.local


cat << EOR >> /etc/alsa/conf.d/asound.conf
pcm.!amiga {
  type plug
  slave {
    pcm pipe
    format s8
    rate 18000
    channels 2
  }
  hint {
    description "Play audio to Amiga using A314"
  }
}
pcm.pipe {
  type file
  format raw
  file "/tmp/piaudio_pipe"
  slave.pcm null
}
EOF
';

touch ~/.asoundrc 
sudo chmod a-w ~/.asoundrc

sudo sh -c '
echo '#!/bin/sh' > /usr/local/bin/playmusic; 
echo 'find ./ -type f -iname "*.mp3" | sort > ./mp3list' >> /usr/local/bin/playmusic;
echo 'mpg123 -a amiga -@./mp3list' >> /usr/local/bin/playmusic;
echo 'rm ./mp3list' >> /usr/local/bin/playmusic;
chmod a+x /usr/local/bin/playmusic;
'

# compile flash tools

sudo apt install libftdi1-2 libftdi1-dev libhidapi-hidraw0 libhidapi-dev libudev-dev zlib1g-dev cmake pkg-config make g++ libgpiod-dev &

cd 
$(git clone https://github.com/trabucayre/openFPGALoader.git
cd openFPGALoader/
mkdir build 
cd build/

sudo apt install libftdi1-2 libftdi1-dev libhidapi-hidraw0 libhidapi-dev libudev-dev zlib1g-dev cmake pkg-config make g++ libgpiod-dev

cmake ..
make

./openFPGALoader -c libgpiod --pins 10:8:11:9 --detect

# cd
wget https://raw.githubusercontent.com/Eriond/clockport_pi_interface/main/HDL/cp_pi_if-10.jed
./openFPGALoader -c libgpiod --pins 10:8:11:9 -f cp_pi_if-10.jed

